#!/bin/sh

algos="SHA1 SHA256 SHA512 SHA3-512 SM3 BLAKE2S_256 BLAKE2B_512 CRC32 CRC24RFC2440"

test "no" = yes || exit 77
echo "      now running 6 GiB tests for $algos - this can take long"
exec ./hashtest --hugeblock --gigs 6 $algos
